### ISSUE TITLE
Accuracy

### ISSUE THREAD

**Issue by LexiRyedale** [JorenSix/PiPePoPo#1]
Since this is billed as a flute-based controller, is there actually a demo of this working with a flute rather than a recorder? 

I was wondering how it would react to the  embouchure pitch-bend that you can do with a flute.

**Comment by JorenSix** [comment]
Hi 

Thanks for the interest! The pitch detection algorithm is called YIN, it was originally developed for speech: it does support short duration pitch-bends or pitch-gestures. In my experience YIN works well for most monophonic semi-harmonic instruments. Please go ahead and try it out with a flute!

J
